In [13]:
import numpy as np
import cv2

In [9]:
n = np.arange(27)
print(n)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


In [10]:
print(n.reshape(3, 3, 3))

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [17]:
im_g = cv2.imread("C:\\Users\\pato1\\OneDrive\\Documentos\\PythonMegaCourse\\modules\\module14\\smallgray.png", 0) #0 for greyscale, 1 for rgb
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [18]:
cv2.imwrite("C:\\Users\\pato1\\OneDrive\\Documentos\\PythonMegaCourse\\modules\\module14\\newsmallgray.png", im_g)

True