In [2]:
import cv2 

In [3]:
img = cv2.imread("C:\\Users\\pato1\\OneDrive\\Documentos\\PythonMegaCourse\\modules\\module17\\galaxy.jpg", 0)

In [4]:
print(type(img))
print(img)
print(img.shape)
print(img.ndim)

<class 'numpy.ndarray'>
[[14 18 14 ... 20 15 16]
 [12 16 12 ... 20 15 17]
 [12 13 16 ... 14 24 21]
 ...
 [ 0  0  0 ...  5  8 14]
 [ 0  0  0 ...  2  3  9]
 [ 1  1  1 ...  1  1  3]]
(1485, 990)
2


In [8]:
width = int(img.shape[1] / 2)
height = int(img.shape[0] / 2)
resized_img = cv2.resize(img, (width, height))
cv2.imwrite("galaxy_resized.jpg", resized_img)
cv2.imshow("Galaxy", resized_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [6]:
#Exercise change resolution to 100x100
img_kangoroos = cv2.imread("C:\\Users\\pato1\\OneDrive\\Documentos\\PythonMegaCourse\\modules\\module17\\kangaroos-rain-australia_71370_990x742.jpg", 1)
img_lighthouse = cv2.imread("C:\\Users\\pato1\\OneDrive\\Documentos\\PythonMegaCourse\\modules\\module17\\Lighthouse.jpg", 1)
img_moon = cv2.imread("C:\\Users\\pato1\\OneDrive\\Documentos\\PythonMegaCourse\\modules\\module17\\Moon sinking, sun rising.jpg", 1)

width = 100
height = 100

kangoroos_resized = cv2.resize(img_kangoroos, (width, height))
lighthouse_resized = cv2.resize(img_lighthouse, (width, height))
moon_resized = cv2.resize(img_moon, (width, height))

cv2.imshow("Kangoroos Resized", kangoroos_resized)
cv2.imshow("Lighthouse Resized", lighthouse_resized)
cv2.imshow("Moon Resized", moon_resized)

cv2.imwrite("kangoroos_resized.jpg", kangoroos_resized)
cv2.imwrite("lighthouse_resized.jpg", lighthouse_resized)
cv2.imwrite("moon_resized.jpg", moon_resized)

cv2.waitKey(0)  # Wait until a key is pressed
cv2.destroyAllWindows()


In [9]:
import cv2
import glob

images=glob.glob("*.jpg")

for image in images:
    img=cv2.imread(image,0)
    re=cv2.resize(img,(100,100))
    cv2.imshow("Hey",re)
    cv2.waitKey(500)
    cv2.destroyAllWindows()
    #cv2.imwrite("resized_"+image,re)